### #numpy


NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".



In [40]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [41]:
import numpy as np
print(np.__version__)

2.4.2


### 0-D Arrays

In [42]:
import numpy as np
arr=np.array(22)
print(arr)
print(arr.ndim ,"Dimension")

22
0 Dimension


### 1-D Arrays

In [43]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim,"Dimension")

[1 2 3 4 5]
1 Dimension


### 2-D Arrays

In [44]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim,"Dimension")


[[1 2 3]
 [4 5 6]]
2 Dimension


### 3-D arrays


In [45]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim,"Dimension")


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3 Dimension


### Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [46]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(f"number of dimension : {arr.ndim}")

[[[[[1 2 3 4 5]]]]]
number of dimension : 5


### Access Array Elements

In [47]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])


1


### Sum of element


In [48]:
print(arr[0]+arr[2])

4


<!-- add  element -->

### Access 2-D Arrays

In [49]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,2])
print('3th element on 2nd row: ', arr[1, 4])

8
3th element on 2nd row:  10


# NumPy Array Slicing

Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[1:])
print(arr[:5])
print(arr[:])
print(arr[0:0])


[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4 5]
[1 2 3 4 5 6 7]
[]


### Negative Slicing

In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


### STEP

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:5:2])

[1 3 5]


## Slicing 2-D Arrays

In [53]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print (arr [1,0:4])

[6 7 8 9]


In [54]:
# From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1])

[2 7]


# NumPy Data Types

Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

### Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [55]:
import numpy as np 
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


### Creating Arrays With a Defined Data Type

In [56]:
import numpy as np 
arr=np.array([1,2,3,4],dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


### Converting Data Type on Existing Arrays

In [57]:
#Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

new_arr = arr.astype(int)

print(new_arr)
print(new_arr.dtype)

[1 2 3]
int64


### NumPy Array Copy vs View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

print("becoz : The copy SHOULD NOT be affected by the changes made to the original array.")

[42  2  3  4  5]
[1 2 3 4 5]
becoz : The copy SHOULD NOT be affected by the changes made to the original array.


In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
print("Becoz: The view SHOULD be affected by the changes made to the original array.")

[42  2  3  4  5]
[42  2  3  4  5]
Becoz: The view SHOULD be affected by the changes made to the original array.


## Shape and Reshaping in NUMPY 

In [60]:
import numpy as np 
arr=np.array([[1,2,3],[1,2,3]])
print(arr)
print()
print(arr.ndim)
print()
print(arr.shape)

[[1 2 3]
 [1 2 3]]

2

(2, 3)


In [61]:
arr=np.array([1,2,3,4], ndmin=4)
print(arr)
print(arr.ndim)
print()
print(arr.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


### Reshape(number of rows ,no of elements) for 2D

In [62]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)
print()
x=arr.reshape(3,2)

print(x)
print(x.ndim)


[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


### Reshape(number of rows ,2ND NUM OF ROW , no of elements) for 3D

In [63]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(arr.ndim)
print()
x=arr.reshape(2,2,3)

print(x)
print(x.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


IF u want to reshape in 1D array

In [64]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

NumPy Array Iterating
